'use client'

import { useState } from 'react'
import { motion } from 'framer-motion'
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { CopyButton } from '@/components/CopyButton'

export default function RandomBytes() {
  const [count, setCount] = useState(16)
  const [result, setResult] = useState('')

  const generateBytes = () => {
    const bytes = new Uint8Array(count)
    crypto.getRandomValues(bytes)
    setResult(Array.from(bytes, (byte) => byte.toString(16).padStart(2, '0')).join(' '))
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center space-x-4">
        <Label htmlFor="count">Number of bytes:</Label>
        <Input
          id="count"
          type="number"
          min="1"
          value={count}
          onChange={(e) => setCount(parseInt(e.target.value))}
          className="w-20"
        />
      </div>
      <Button onClick={generateBytes}>Generate Bytes</Button>
      {result && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="p-4 bg-secondary rounded-md"
        >
          <h3 className="text-lg font-semibold mb-2">Generated Bytes:</h3>
          <div className="flex items-center">
            <p className="text-2xl font-mono break-all">{result}</p>
            <CopyButton text={result} />
          </div>
        </motion.div>
      )}
    </div>
  )
}

